// Copyright (c) 2026 The Cochran Block. All rights reserved.
//! f90 f91 f92 f109 — cloudflared child of approuter. Config generated in data/cloudflared.yml.

use crate::registry;
use sha2::{Digest, Sha256};
use std::collections::HashSet;
use std::path::Path;
use std::process::{Child, Command, Stdio};

/// Default tunnel ID when CF_TUNNEL_ID unset.
const DEFAULT_TUNNEL_ID: &str = "b12525df-6971-4c47-9a0d-61ee57a5cbd5";

/// Tunnel ID from env or default.
pub fn tunnel_id() -> String {
    std::env::var("CF_TUNNEL_ID")
        .or_else(|_| std::env::var("CLOUDFLARE_TUNNEL_ID"))
        .unwrap_or_else(|_| DEFAULT_TUNNEL_ID.into())
}

const c92: &str = "2026.2.0";

#[cfg(all(target_os = "windows", target_arch = "x86_64"))]
const CLOUDFLARED_FILENAME: &str = "cloudflared-windows-amd64.exe";
#[cfg(all(target_os = "windows", target_arch = "x86_64"))]
const CLOUDFLARED_SHA256: &str = "b3279f2186a1c3c438ad5865e802bbbec26090c5d3fdb4ac1113f1143a94837a";

#[cfg(all(target_os = "linux", target_arch = "x86_64"))]
const CLOUDFLARED_FILENAME: &str = "cloudflared-linux-amd64";
#[cfg(all(target_os = "linux", target_arch = "x86_64"))]
const CLOUDFLARED_SHA256: &str = "176746db3be7dc7bd48f3dd287c8930a4645ebb6e6700f883fddda5a4c307c16";

#[cfg(not(any(
    all(target_os = "windows", target_arch = "x86_64"),
    all(target_os = "linux", target_arch = "x86_64")
)))]
const CLOUDFLARED_FILENAME: &str = "";
#[cfg(not(any(
    all(target_os = "windows", target_arch = "x86_64"),
    all(target_os = "linux", target_arch = "x86_64")
)))]
const CLOUDFLARED_SHA256: &str = "";

/// f90 = cloudflared_path. Prefers base/approuter/bin, then base/bin, else bare name.
fn f90(p0: &Path) -> std::path::PathBuf {
    let v0 = if cfg!(target_os = "windows") { "cloudflared.exe" } else { "cloudflared" };
    for base in [p0.join("approuter"), p0.to_path_buf(), p0.parent().unwrap_or(p0).to_path_buf()] {
        let v1 = base.join("bin").join(v0);
        if v1.exists() {
            return v1;
        }
    }
    std::path::PathBuf::from(v0)
}

fn credentials_path() -> String {
    if let Ok(p) = std::env::var("CLOUDFLARED_CREDENTIALS") {
        return p;
    }
    let tid = tunnel_id();
    dirs::home_dir()
        .map(|h| h.join(".cloudflared").join(format!("{}.json", tid)))
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_else(|| format!("~/.cloudflared/{}.json", tid))
}

/// f91 = generate cloudflared config in data/. Ingress from registry only — apps must register via API.
pub fn f91_gen(p0: &Path, reg: &registry::t32, port: u16) -> Result<std::path::PathBuf, Box<dyn std::error::Error + Send + Sync>> {
    let data = registry::data_dir(p0);
    std::fs::create_dir_all(&data)?;
    let path = data.join("cloudflared.yml");
    let tid = tunnel_id();
    let creds = credentials_path();
    let service = std::env::var("CLOUDFLARED_TUNNEL_SERVICE")
        .unwrap_or_else(|_| format!("http://127.0.0.1:{}", port));
    let hostnames: HashSet<String> = reg.hostname_map().into_keys().collect();
    let mut lines: Vec<String> = vec![
        "# Generated by approuter. Do not edit.".into(),
        format!("tunnel: {}", tid),
        format!("credentials-file: {}", creds),
        String::new(),
        "ingress:".into(),
    ];
    for h in hostnames {
        let host = if h.contains('*') { format!("\"{}\"", h) } else { h };
        lines.push(format!("  - hostname: {}", host));
        lines.push(format!("    service: {}", service));
    }
    lines.push("  - service: http_status:404".into());
    lines.push(String::new());
    std::fs::write(&path, lines.join("\n"))?;
    Ok(path)
}

/// f92 = tunnel_spawn. Generates config from registry, spawns cloudflared. Caller must kill on shutdown.
pub fn f92(p0: &Path, reg: &registry::t32, port: u16) -> Result<Child, Box<dyn std::error::Error + Send + Sync>> {
    let v0 = f90(p0);
    let v1 = f91_gen(p0, reg, port)?;
    let mut v2 = Command::new(&v0);
    v2.arg("tunnel").arg("--config").arg(&v1).arg("run").arg(tunnel_id())
        .stdin(Stdio::null()).stdout(Stdio::inherit()).stderr(Stdio::inherit());
    v2.env_remove("TUNNEL_TOKEN");
    let v3 = v2.spawn()?;
    tracing::info!("Cloudflare Tunnel started (config={})", v1.display());
    Ok(v3)
}

/// f109 = ensure_cloudflared. Use base/bin or parent/bin (cochranblock). Download to base/bin/ if missing.
pub async fn f109(base: &Path) -> Result<bool, Box<dyn std::error::Error + Send + Sync>> {
    let bin_name = if cfg!(target_os = "windows") {
        "cloudflared.exe"
    } else {
        "cloudflared"
    };
    for search_base in [base.join("approuter"), base.to_path_buf(), base.parent().unwrap_or(base).to_path_buf()] {
        let dest = search_base.join("bin").join(bin_name);
        if dest.exists() && dest.metadata().map(|m| m.len() > 0).unwrap_or(false) {
            tracing::info!("cloudflared already present: {}", dest.display());
            return Ok(true);
        }
    }
    let bin_dir = if base.join("approuter").exists() {
        base.join("approuter").join("bin")
    } else {
        base.join("bin")
    };
    let dest = bin_dir.join(bin_name);
    if CLOUDFLARED_FILENAME.is_empty() {
        return Err("ensure-cloudflared: unsupported platform (need Windows x86_64 or Linux x86_64)".into());
    }
    let url = format!(
        "https://github.com/cloudflare/cloudflared/releases/download/{}/{}",
        c92,
        CLOUDFLARED_FILENAME
    );
    tracing::info!("Downloading cloudflared {} for {}...", c92, std::env::consts::OS);
    let client = reqwest::Client::builder()
        .user_agent("approuter/1.0")
        .build()?;
    let bytes = client.get(&url).send().await?.bytes().await?;
    let got_sha = format!("{:x}", Sha256::digest(&bytes));
    if got_sha != CLOUDFLARED_SHA256 {
        return Err(format!("cloudflared checksum mismatch: got {}, expected {}", got_sha, CLOUDFLARED_SHA256).into());
    }
    std::fs::create_dir_all(&bin_dir)?;
    std::fs::write(&dest, &bytes)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&dest)?.permissions();
        perms.set_mode(0o755);
        std::fs::set_permissions(&dest, perms)?;
    }
    tracing::info!("cloudflared installed: {}", dest.display());
    Ok(true)
}
